#!/usr/bin/env bash
# print details obout the domains and subdomains


print_domain_subdomain () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then

    print_domain_subdomain "$1" "www"
  	print_domain_subdomain "$1" "lb-01"
  	print_domain_subdomain "$1" "web-01"
  	print_domain_subdomain "$1" "web-02"
elif [ "$#" == 2 ]
then
	print_domain_subdomain "$1" "$2"
fi
