#!/usr/bin/env bash
# installs nginx server
apt-get update
apt-get -y install nginx

# nginx profile opening only port 80
ufw allow 'Nginx HTTP'

# create index.html
echo "Hello World!" > /var/www/html/index.html
service nginx start
