#!/usr/bin/env bash
# installs nginx server
sudo apt-get update
sudo apt-get -y install nginx

# nginx profile opening only port 80
sudo ufw allow 'Nginx HTTP'

# create index.html
echo "Hello World!" | sudo tee -a /var/www/html/index.html
sudo service nginx start
