#!/usr/bin/env bash
# Configuring a permanent redirection in an Ubuntu machine
sudo apt-get update
sudo apt-get -y install nginx

# nginx profile opening only port 80
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee -a /var/www/html/index.html
sudo sed -i "s/server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
