#!/usr/bin/env bash
# Configuring a permanent redirection in an Ubuntu machine
sudo apt-get update
sudo apt-get -y install nginx

# nginx profile opening only port 80
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee -a /var/www/html/index.html
sudo sed -i "/^server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo sed -i "/^redirect_me/ a\\\terror_page 404 /404.html;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/404.html
sudo service nginx start
