#!/usr/bin/env bash
# Configuring a permanent redirection in an Ubuntu machine
sudo apt-get update
sudo apt-get -y install nginx

# nginx profile opening only port 80
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee -a /var/www/html/index.html

# Set up redirection using sed for specified url
sudo sed -i '/listen \[::\]:80 default_server/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/404.html

# Set up the custom 404 page using sed
sudo sed -i '/error_page 404/c \\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

sudo service nginx start
