#!/usr/bin/env bash
# Configuring a permanent redirection in an Ubuntu machine
sudo apt-get update
sudo apt-get -y install nginx

# nginx profile opening only port 80
sudo ufw allow 'Nginx HTTP'

# Create index.html
echo "Hello World!" | sudo tee -a /var/www/html/index.html

# Add custom header configuration and set redirection
sudo sed -i '/listen \[::\]:80 default_server/a \\n\tadd_header X-Served-By $hostname;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/404.html

# Configure nginx to use custom 404 page
sudo sed -i '/listen \[::\]:80 default_server/a \\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo service nginx start



