#!/usr/bin/env bash
# installing haproxy

# Create backup of the HAProxy configuration file
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}

# Configure HAProxy
sudo sed -i '/^frontend http_frontend/a \    bind *:80\n    mode http\n    default_backend http_backend' /etc/haproxy/haproxy.cfg
sudo sed -i '/^backend http_backend/a \    balance roundrobin\n    server web-01 	52.91.146.214:80 check\n    server web-02 54.160.76.161:80 check' /etc/haproxy/haproxy.cfg

# Enable HAproxy to be started by an init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
