#!/usr/bin/env bash
# configuring haproxy

# Create backup of the HAProxy configuration file
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}

# Configure HAProxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http-frontend
        bind *:80
        mode http
        default_backend http_backend
backend http_backend
        balance roundrobin
        server web-01 52.91.146.214:80 check
        server web-02 54.160.76.161:80 check
EOT

# sudo sed -i '/^frontend http_frontend/a \\n\t\tbind *:80\n\t\tmode http\n\t\tdefault_backend http_backend' /etc/haproxy/haproxy.cfg
# sudo sed -i '/^backend http_backend/a \\n\t\tbalance roundrobin\n\t\tserver web-01 52.91.146.214:80 check\n\t\tserver web-02 54.160.76.161:80 check' /etc/haproxy/haproxy.cfg

# Enable HAproxy to be started by an init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
