#!/usr/bin/env bash
# Configure a Nginx server to run and listen to port 80.

# Check if nginx is installed
# Install Nginx if not installed
if [ ! $(command -v nginx) ]; then
    sudo apt-get update
    sudo apt-get -y install nginx
fi

# Stop nginx if it's already running
sudo service nginx stop

# Delete ~/sites-enabled/default
sudo rm /etc/nginx/sites-enabled/default

# S-link default file in sites-available with sites-enabled
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Start nginx
sudo service nginx start
