#!/usr/bin/env bash
# Configure a Nginx server to run and listen to port 80.

# Delete ~/sites-enabled/default
sudo rm /etc/nginx/sites-enabled/default

# S-link default file in sites-available with sites-enabled
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx
sudo service nginx restart
