#!/usr/bin/env bash
# Configure a Nginx server to run and listen to port 80.

# Check if nginx is installed
if [ ! $(command -v nginx) ]; then
  echo "Nginx is not installed, please install it first."
  exit 1
fi

# Stop nginx if it's already running
sudo service nginx stop

# Update Nginx configuration
rm /etc/nginx/sites-enabled/default

# S-link default file in sites-available with sites-enabled
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Start nginx
sudo service nginx start
